apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-{{ .Values.volume.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi