image:
  repository: ghcr.io/qdm12/gluetun
  pullPolicy: IfNotPresent

volume:
  name: gluetun-config

secret:
  name: gluetun-credentials
  data:
    OPENVPN_USER: ""
    OPENVPN_PASSWORD: ""

configMap:
    name: gluetun-config
    data:
      TZ: "Europe/Berlin"
      VPN_SERVICE_PROVIDER: "perfect privacy"
      SERVER_CITIES: "Amsterdam"